export const TYPES = {
	Application: Symbol.for('Application'),
	LoggerService: Symbol.for('LoggerService'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UserRepository: Symbol.for('UserRepository'),
	AWSController: Symbol.for('AWSController'),
	AWSService: Symbol.for('AWSService'),
	S3Service: Symbol.for('S3Service'),
	DynamoDBService: Symbol.for('DynamoDBService'),
	SQSService: Symbol.for('SQSService'),
};
